import './globals.css';
import type { Metadata } from 'next';
import { Locale, i18n } from '@/i18n.config';
import Header from './components/header';

import { Inter } from 'next/font/google';
import TranslateProvider from '@/providers/TranslateProvider';
import { getDictionary } from '@/lib/dictionary';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export async function generateStaticParams() {
	return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({
	children,
	params,
}: {
	children: React.ReactNode;
	params: { lang: Locale };
}) {
	const page = await getDictionary(params.lang);
	return (
		<html lang={params.lang}>
			<body className={inter.className}>
				<Header lang={params.lang} />
				<TranslateProvider dictionary={page}>
					<main>{children}</main>
				</TranslateProvider>
			</body>
		</html>
	);
}
