import Header from '../components/header';

import type { Metadata } from 'next';
import { Locale, i18n } from '@/i18n.config';

import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export async function generateStaticParams() {
	return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function MainLayout({ children, params }: { children: React.ReactNode; params: { lang: Locale } }) {
	return (
		<section className='11'>
			<Header lang={params.lang} />
			{children}
		</section>
	);
}
